sudo: required

language: python

dist: xenial

python:
  - "2.7"

virtualenv:
  system_site_packages: true

services:
  - docker
  - postgresql

addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.4

env:
  - BACKEND: 'geonode.geoserver'
    ON_TRAVIS: 'True'
  - BACKEND: 'geonode.qgis_server'
    DOCKER_COMPOSE_VERSION: 1.11.2
    # This is qgis server address
    QGIS_SERVER_URL: http://localhost:9000/
    # This is the location of docker network bridge
    # So QGIS server can access this address
    SITEURL: http://localhost:8000/
    QGIS_SERVER_PORT: 9000
    ON_TRAVIS: 'True'
    CELERY_ALWAYS_EAGER: 'True'

branches:
  only:
    - 2.8.x-qgis_server
    - master
    - 2.9.x
    - 2.7.x
    - 2.6.x

before_install:
  - scripts/misc/qgis_server_setup.sh before_install
  - scripts/misc/geoserver_setup_patch.sh before_install
  - chmod +x scripts/misc/bdd_setup.sh
  - scripts/misc/bdd_setup.sh before_install

install:
  - sudo apt-get -qq -y update
  - sudo apt-get install -y libgdal1i python-gdal gdal-bin spatialite-bin;
  - sudo apt-get install -y python-virtualenv python-imaging python-lxml python-pyproj python-shapely python-httplib2 python-httplib2 gettext;
  - sudo apt-get install -y python-dev libxml2 libxml2-dev libxslt1-dev zlib1g-dev libjpeg-dev libpq-dev libgdal-dev git default-jdk;
  - sudo add-apt-repository -y ppa:webupd8team/java; sudo apt update;
  - echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections;
  - echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections;
  - sudo apt install -y openjdk-8-jre openjdk-8-jdk ant maven;
  - sudo update-java-alternatives --set java-1.8.0-openjdk-amd64;
  - export JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:bin/java::")
  - export PATH=$JAVA_HOME'bin/java':$PATH
  - sudo apt-get update
  - pip install -r requirements.txt --no-deps
  - pip install -e .
  - pip install pygdal==`gdal-config --version`.*;
  - pip install codecov

before_script:
  # Initialize DB
  # - sudo apt-get install postgresql-9.6-postgis-2.3 -y -q
  - psql -U postgres -c "create extension postgis"
  - chmod +x scripts/misc/create_dbs_travis.sh
  - scripts/misc/create_dbs_travis.sh before_script
  # For QGIS Server Travis steps
  - scripts/misc/qgis_server_setup.sh before_script
  - scripts/misc/bdd_setup.sh before_script

  # Temporary Patch for Geoserver Travis Unittests
  # Should be cleaned up after paver setup_geoserver run normally
  - scripts/misc/geoserver_setup_patch.sh before_script

  - paver setup

script:
  - paver run_tests --coverage --local false

after_script:
  # For QGIS Server Travis steps
  - scripts/misc/qgis_server_setup.sh after_script

  # Cleanup
  - paver reset_hard

after_success:
  - codecov

#notifications:
#  irc:
#    channels:
#      - "irc.freenode.org#geonode"
#    use_notice: true
#  email:
#    - alessio.fabiani@gmail.com
#    - ingenieroariel@gmail.com
#    - simone.dalmasso@gmail.com
#  slack: geonode-sprint:oQylJRkU9feZ8JruGi6czWwe
